spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

pokemon-tcg:
  api-key: ${POKEMON_TCG_API_KEY}
  base-url: https://api.pokemontcg.io/v2
  connect-timeout: 30000
  read-timeout: 30000
